title: Chengxi Wu # your name (or website title) here
logo: "/images/Screenshot 2023-03-24 142207.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br> 
  < a href="pdf/Resume.pdf"btn btn--info">Resume</ a>  
  <br> 
  < a href="https://www.GitHub.com/ChengxiWulehigh/">GitHub</ a>  
  <br> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
